### ISSUE TITLE
MLflow documentation

### ISSUE THREAD

**Issue by gmertes** [ecmwf/anemoi-training#4]
### Is your feature request related to a problem? Please describe.

We need to document the MLflow parts of the package. 

### Describe the solution you'd like

Document:
- how token authentication is handled and how it works with our new mlflow server 
- the `anemoi-training mlflow` command and its subcommands (login, sync, ...)
- naming conventions for mlflow experiment names
- anything else?

Most of this (especially things related to the new mlflow server) are only relevant for internal users and member states. This stuff should probably go in Confluence, with the GitHub docs being just an API reference and maybe some general explanations of why these things exist.

Docs on how the token authentication works can be copied from #2

**Comment by HCookie** [comment]
Was this addressed with Release 0.2?
