### ISSUE TITLE
Mlflow log_params string truncation

### ISSUE THREAD

**Issue by anaprietonem** [ecmwf/anemoi-training#69]
### What happened?

When logging parameters in mlflow we are truncating the strings to 250 characters. This might be an issue with very long string but also with lists of strings or nested dicts.

### What are the steps to reproduce the bug?

Run anemoi-training train with MlFlow tracking enabled

### Version

0.1.0

### Platform (OS and architecture)

ATOS

**Comment by MeraX** [comment]
Thanks for opening the issue.

**Comment by HCookie** [comment]
Apologies, #88, merely provides a mitigation for this issue, but more work will be needed to fully address the problem.
